db.url=jdbc:mysql://localhost:3306/Inventory_Management_db
db.username=root
db.password=Root123
db.driver=com.mysql.cj.jdbc.Driver
logging.level.root=INFO
logging.level.com.kovanlabs.project=DEBUG
sms.enabled=true
sms.api.url=https://www.fast2sms.com/dev/bulkV2
sms.api.key=SIMULATOR
sms.sender.id=FSTSMS
sms.route=q
sms.language=english

# Mail configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=premalatha.pragasam.p2004@gmail.com
spring.mail.password=ofrnyubztrvqwayd
