db.url=jdbc:mysql://localhost:3306/Inventory_Management_db
db.username=root
db.password=Root123
db.driver=com.mysql.cj.jdbc.Driver
logging.level.root=INFO
logging.level.com.kovanlabs.project=DEBUG
sms.enabled=false
sms.api.url=
sms.api.key=
sms.sender.id=Ventorie