db.url=jdbc:mysql://localhost:3306/Inventory_Management_db
db.username=root
db.password=root
db.driver=com.mysql.cj.jdbc.Driver
logging.level.root=INFO
logging.level.com.kovanlabs.project=DEBUG
sms.enabled=true
sms.api.url=https://www.fast2sms.com/dev/bulkV2
sms.api.key=stREyaDqMiLun12rfTxQNd4XbC5wVWJ8jovZYB6k7SFI0cphAK6G84BVPAI29pEYZc1ue0JhzLTFMiox
sms.sender.id=FSTSMS
sms.route=q
sms.language=english
